# Generated by Django 2.0.3 on 2018-03-11 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('FR', 'Open'), ('CL', 'Closed'), ('CN', 'Cancelled')], default='FR', max_length=2)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'db_table': '"lots"',
                'ordering': ('-start_date', 'end_date', 'winner'),
            },
        ),
    ]
